PT:
  PID_Theta:
    Kp: 10
    Ki: 0
    Kd: 0
  PID_Distance:
      Kp: 5.
      Ki: 0.
      Kd: 0
  velocity_limit: 2.0
  acceleration_limit: 20

RT:
  linear_velocity_cap: 4.0
  angular_velocity_cap: 4.0
  warning_radius: 2.5
  escape_distance: 1.0